### Get /
GET http://localhost:7777


### register
POST http://localhost:7777/auth/register
Content-Type: application/json

{
    "username": "lebronjames",
    "password": "goatofbasketball123"
}


### login
POST http://localhost:7777/auth/login
Content-Type: application/json

{
    "username": "lebronjames",
    "password": "goatofbasketball123"
}